services:
  postgres:
    image: postgres:16-alpine
    container_name: kyc-postgres
    environment:
      POSTGRES_USER: kyc
      POSTGRES_PASSWORD: kyc
      POSTGRES_DB: kyc
    ports:
      - "5433:5432"
    volumes:
      - kyc-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kyc -d kyc"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: kyc-redis
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - kyc-redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  minio:
    image: minio/minio:latest
    container_name: kyc-minio
    environment:
      MINIO_ROOT_USER: kycadmin
      MINIO_ROOT_PASSWORD: kycadminsecret
    command: server /data --console-address ":9011"
    ports:
      - "9010:9000"
      - "9011:9011"
    volumes:
      - kyc-miniodata:/data

volumes:
  kyc-pgdata:
  kyc-redisdata:
  kyc-miniodata:
